function showFunction(part) {
  let message;
  if (part == 'right lobe') {
    message = "The right lung consists of three lobes:\nThe Superior, Middle, and Inferior lobes.\n\n• It's shorter than the left lung but wider than the left lung.";
  } else if (part == 'respiratory system'){
    message = "The cells of the human body require a constant stream of oxygen to stay alive.\n\nThe respiratory system provides oxygen to the body's cells while removing carbon dioxide, a waste product that can be lethal if allowed to accumulate.\n\nThere are 3 major parts of the respiratory system:\nThe Airway, the Lungs, and the Muscles of Respiration.\n\nThe airway, which includes the nose, mouth, pharynx, larynx, trachea, bronchi, and bronchioles, carries air between the lungs and the body's exterior.\n\nThe lungs act as the functional units of the respiratory system by passing oxygen into the body and carbon dioxide out of the body.\n\nFinally, the muscles of respiration, including the diaphragm and intercostal muscles, work together to act as a pump, pushing air into and out of the lungs during breathing.";
  } else if (part == 'nasal cavity') {
    message = "The nose and nasal cavity form the main external opening for the respiratory system and are the first section of the body's airway---the respiratory tract through which air moves.\n\nThe nose is a structure of the face made of cartilage, bone, muscle, and skin that supports and protects the anterior portion of the nasal cavity.\n\nThe nasal cavity is a hollow space within the nose and skull that is lined with hairs and mucus membrane.\n\nThe function of the nasal cavity is to warm, moisturize, and filter air entering the body before it reaches the lungs.\n\nHairs and mucus lining the nasal cavity help to trap dust, mold, pollen and other environmental contaminants before they can reach the inner portions of the body. Air exiting the body through the nose returns moisture and heat to the nasal cavity before being exhaled into the environment.";
  } else if (part == 'pharynx') {
    message = "The pharynx, also known as the throat, is a multitasking muscular funnel that helps you breathe and directs food and liquid to the digestive system.\n\nSpecifically, the pharynx:\n• Routes air coming in the nose and mouth down to the larynx (voice box), which, in turn, moves air to the trachea and lungs.\n\n• Delivers food and liquid to the esophagus, which sends them on to the stomach.\n\n• More than that, the pharynx helps to make sure particles of food and liquid don’t tumble into the trachea and the lungs.\n\nThe EPIGLOTTIS is a flap of elastic cartilage that acts as a switch between the trachea and the esophagus.\n• Because the pharynx is also used to swallow food, the epiglottis ensures that air passes into the trachea by covering the opening to the esophagus.";
  } else if (part == 'trachea') {
    message = "The trachea's, also known as the windpipe, main function is to carry air in and out of the lungs.\nBecause it’s a stiff, flexible tube, it provides a reliable pathway for oxygen to enter the body.\n\nthe trachea works with the rest of the respiratory system to help you breathe. When you inhale, air moves:\n• From the nose and mouth into the trachea.\n• From the trachea into the left and right bronchi.\n• Through the bronchi and into bronchioles in the lungs.\n• Into small sacs in the lungs called alveoli, where the body exchanges oxygen for carbon dioxide (gas exchange).\n\nWhen you breathe out or exhale, the body performs these motions in reverse to carry carbon dioxide out of the body.";
  } else if (part == 'diaphragm') {
    message = "The diaphragm in the respiratory system is the dome-shaped sheet of muscle that separates the chest from the abdomen.\n\nIt is also referred to the thoracic diaphragm because it's located in the thoracic cavity, or chest.\n\nIt is attached to the spine, ribs and sternum and is the main muscle of respiration, playing a very important role in the breathing process. ";
  } else if (part == 'oral cavity') {
    message = "The mouth, also known as the oral cavity, is the secondary external opening for the respiratory tract.\n\nMost normal breathing takes place through the nasal cavity, but the oral cavity can be used to supplement or replace the nasal cavity's functions when needed.\n\nBecause the pathway of air entering the body from the mouth is shorter than the pathway for air entering from the nose, the mouth does not warm and moisturize the air entering the lungs as well as the nose performs this function. The mouth also lacks the hairs and sticky mucus that filter air passing through the nasal cavity.\n\nThe one advantage of breathing through the mouth is that its shorter distance and larger diameter allows more air to quickly enter the body.";
  } else if (part == 'larynx') {
    message = "The larynx, also known as the voice box, lets air pass from the throat (pharynx) to the trachea on the way to the lungs.\n\nthe larynx is also the reason you’re able to make sounds, it contains the vocal cords, which create sound.";
  } else if (part == 'bronchi') {
    message = "Bronchi are the large tubes that connect to the trachea (windpipe) and direct the air you breathe to the right and left lungs.\n\n• At the inferior end of the trachea, the airway splits into left and right branches known as the PRIMARY BRONCHI.\n• The left and right bronchi run into each lung before branching off into smaller SECONDARY BRONCHI. The secondary bronchi carry air into the lobes of the lungs (2 in the left lung and 3 in the right lung).\n• The secondary bronchi in turn split into many smaller TERTIARY BRONCHI within each lobe. \n\nThe bronchi also help moisturize the air you breathe and screen out foreign particles: \n\n• the airways are lined with cells that create mucus. The MUCUS keeps the airways moist. It also traps bacteria, viruses, fungi and other particles to protect the lungs and prevent infection.\n\n• The bronchi are lined with CILIA, tiny hairlike structures. The cilia help move mucus (phlegm) and particles out of the lungs. When you cough or swallow, the particles trapped in the mucus move out of the body or into the digestive tract, where the body can dispose of them.";
  } else if (part == 'bronchus') {
    message = "A crucial part of the respiratory system, the bronchi function primarily as passageways for air...";
  } else if (part == 'bronchioles') {
    message = "Tertiary bronchi split into many smaller bronchioles that spread throughout the lungs.\n\nEach bronchiole further splits into many smaller branches less than a millimeter in diameter called terminal bronchioles.\n\nFinally, the millions of tiny terminal bronchioles conduct air to the alveoli of the lungs.";
  } else if (part == 'alveoli') {
    message = "The alveoli are the very small air sacs where the exchange of oxygen and carbon dioxide takes place.\n\nCAPILLARIES are blood vessels in the walls of the alveoli.\n• Blood passes through the capillaries, entering through the PULMONARY ARTERY and leaving via the PULMONARY VEIN.\n• While in the capillaries, blood gives off carbon dioxide through the capillary wall into the alveoli and takes up oxygen from air in the alveoli.";
  } else if (part == 'lungs') {
    message = "The lungs make oxygen available to the body (inspiration) and remove other gases (expiration), such as carbon dioxide, from the body.\n\nAfter absorbing oxygen, the blood leaves the lungs and is carried to the heart. From there, it’s pumped through the body to provide oxygen to the cells of the tissues and organs.\n\nWhen cells use oxygen, they produce carbon dioxide and transfer it to the blood. the bloodstream carries the carbon dioxide back to the lungs. When you exhale, you remove the carbon dioxide.\n\nthe respiratory system prevents harmful substances from entering the lungs by using:\n• Small hairs in the nose that act as an air-cleaning system and help filter out large particles.\n• Mucus produced in the trachea and bronchial tubes to keep air passages moist and help catch dust, bacteria and other substances.\n •The sweeping motion of cilia (small hairs in the respiratory tract) to keep air passages clean.\n\nThe lungs are separated by the mediastinum. This area contains the heart, trachea, esophagus, and many lymph nodes. The lungs are covered by a protective membrane known as the pleura and are separated from the abdominal cavity by the muscular diaphragm.";
  } else if (part == 'pulmonary arteries') {
    message = "The pulmonary arteries are blood vessels that carry oxygen-poor blood from the right side of the heart to the lungs.\n\nThe blood needs to reach the lungs to gain oxygen and get rid of waste products like carbon dioxide. This blood then returns to the heart, and the heart pumps it out to the rest of the body. \n\nIn medical terms, the word “pulmonary” means something that affects the lungs.";
  } else if (part == 'pulmonary veins') {
    message = "The pulmonary veins are blood vessels that carry oxygen-rich blood from the lungs to the heart.\n\nFrom there, the heart sends the blood to all the other organs and tissues.";
  } else if (part == 'left lobe') {
    message = "The left lung has two lobes:\nThe Superior and the Interior.\n\nThe left lung is smaller than the right because the heart is where the middle lobe on the left lung would be. The left lung has two parts that the right lung doesn’t have: the cardiac notch and the lingula, an extension of the superior lobe.\n\nThe CARDIAC NOTCH is an indentation on the surface of the left lung, and it allows space for the heart ";
  }  else if (part == 'rib cage') {
    message = "The rib cage surrounds and protects the vital organs in the chest cavity, the heart and lungs. It expands with the lungs when you breathe.\n\nAs part of the axial skeleton, the rib cage helps form the trunk of the body. It also serves as an attachment point for core muscles, like the diaphragm.";
  } else {
    message = "Click a part to view its function";
  }
  alert(message);
}
